# Generated by Django 4.2.11 on 2024-04-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='角色名称', max_length=20, verbose_name='角色名称')),
                ('code', models.CharField(help_text='角色编码', max_length=100, verbose_name='角色编码')),
                ('order', models.IntegerField(default=0, help_text='排序', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, help_text='激活', verbose_name='激活')),
                ('menu_list', models.TextField(blank=True, default='', help_text='菜单列表', verbose_name='菜单列表')),
                ('department_list', models.TextField(blank=True, default='', help_text='部门列表', verbose_name='部门列表')),
                ('description', models.CharField(blank=True, default='', help_text='角色描述', max_length=150, verbose_name='角色描述')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='角色', to='user.role', verbose_name='角色'),
        ),
    ]
